### ISSUE TITLE
Plot does not show any coverage

### ISSUE THREAD

**Issue by hoelzer** [jonas-fuchs/BAMdash#12]
Hey!

I am maybe misusing the tool but I have a small FASTA file that I mapped to a SC2 reference and then I wanted to visualize. Attached is the sorted BAM file after mapping with minimap2. 

Then I used

```bash
samtools index baits.sorted.bam
bamdash -b baits.sorted.bam -r NC_045512.2
```

which works without error. But the plot looks like this:

![image](https://github.com/jonas-fuchs/BAMdash/assets/14393703/d3d57efe-32d4-489a-a090-6917815087fa)

What am I missing?

Thx!

[baits.sorted.bam.gz](https://github.com/jonas-fuchs/BAMdash/files/13522855/baits.sorted.bam.gz)

**Comment by jonas-fuchs** [comment]
You sneaky guy. Always with this custom stuff :P. 

So no error on your part, but your "reads" have no quality assigned (standard for the function is 15). Introduced now the -q arg in version 0.2.2. 

Now you can try:

```bash
bamdash -b baits.sorted.bam -r NC_045512.2 -q 0
```
