### ISSUE TITLE
Summary statistics in text file

### ISSUE THREAD

**Issue by KristinaGagalova** [jonas-fuchs/BAMdash#17]
Hi, 

Thank you for this great tool, it's really useful to analyze genomic regions. 

I was wondering: is there possible to output the summary statistics (avg. coverage, reads, GC etc) in a separate txt file? That would be really handy to anayze the results together with the plot

Thanks
Kristina

**Comment by jonas-fuchs** [comment]
Hi Kristina,

So you mean the statistics shown within the plot? Should be easy to link this to the dump command. 

Cheers,
Jonas

**Comment by KristinaGagalova** [comment]
Yes! The same exact statistics but in a text format, nothing too fancy

**Comment by jonas-fuchs** [comment]
Should be fixed in 0.3. If you have any issues please give me some feedback. I also fixed some stuff with the coverage calculations ;)
