### ISSUE TITLE
Name in report do not match the reference name (-r)

### ISSUE THREAD

**Issue by KristinaGagalova** [jonas-fuchs/BAMdash#19]
Hi, 

I am running the following, on the bamdash version 0.3, installed through ```pip```:
```
bamdash -r tig00000043 -b 19Ptm93.lr.sort.bam --dump -q 0
```

The output (html and dump text) does not show the reference name I used. The length of the sequence looks correct, though, so it may be an error in the output/name parsing.
![Capture30](https://github.com/user-attachments/assets/62ec0de2-f627-4686-a9cc-0e7ce0a23183)

Could you please take a look?

Thank you in advance

**Comment by jonas-fuchs** [comment]
Hi Kristina,

thanks for the feedback. You actually found a quite big bug that was in here a while. The statistics for reference, mapped and unmapped are apparently not correct (it always uses the first index). Should be an easy fix but something you never notice until you use this tool for bams mapped to multiple references. I will fix this ASAP! Sry for the inconvenience, but it might be that mapped/unmapped and reference are at the moment not necessarily correct.

Cheers, 
Jonas

**Comment by jonas-fuchs** [comment]
Fix was quite easy. I will double check everything and release 0.3.1 ;)

**Comment by jonas-fuchs** [comment]
Should be fixed now with 0.3.1. Thanks again for the feedback!

**Comment by KristinaGagalova** [comment]
It's correct now! Thank you for the fast fis, I am planning to use this great tool for my pipeline :)
